### ISSUE TITLE
Boiler fails to create a new display

### ISSUE THREAD

**Issue by erlandyt** [mrmrmystery/Boiler#4]
Mod version: Boiler-2.0.6-all.jar
Server version: paper 1.20.2-318. API version: 1.20.2-R0.1-SNAPSHOT
Attempted command: `/boiler display create 634 116 964 638 114 964`

```diff
- [Mon 15:50:58 ERROR Minecraft] Could not pass event PlayerJoinEvent to Boiler v2.0.7
java.lang.NoClassDefFoundError: net/minecraft/network/protocol/game/ServerboundInteractPacket$Handler
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.common.Paper1202Platform.onJoin(Paper1202Platform.java:48)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor279.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:346)
    at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130)
    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18)
    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinish
```
At this point are the regular messages about a player joining and everything looks normal

```diff
  [Mon 15:59:24 INFO  Server/PlayerConnection] Erland_2 issued server command: /boiler display create 634 116 964 638 114 964
- [Mon 15:59:24 ERROR CommandAPI] Unhandled exception executing '/boiler display create 634 116 964 638 114 964'
java.lang.NoSuchMethodError: 'void de.pianoman911.mapengine.api.pipeline.IPipelineContext.bundling(boolean)'
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.core.display.ImplBoilerDisplay.save(ImplBoilerDisplay.java:209)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.core.display.ImplBoilerDisplay.<init>(ImplBoilerDisplay.java:73)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.core.display.ImplDisplayManager.createDisplay(ImplDisplayManager.java:75)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.core.display.ImplDisplayManager.createDisplay(ImplDisplayManager.java:68)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.core.commands.display.DisplayCreateCommand.lambda$new$0(DisplayCreateCommand.java:32)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.commandapi.executors.PlayerCommandExecutor.run(PlayerCommandExecutor.java:48)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:110)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91)
    at Boiler-2.0.7-all.jar//net.somewhatcity.boiler.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:258)
    at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
    at net.minecraft.commands.Commands.performCommand(Commands.java:330)
    at net.minecraft.commands.Commands.performCommand(Commands.java:314)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handle
```
![2024-04-22_17 06 36](https://github.com/mrmrmystery/Boiler/assets/70699100/2564c43f-7b40-4223-8b74-c5f90c42f85c)
Image of the setup. The torches represent the coordinates of the command

**Comment by mrmrmystery** [comment]
Are you using the latest version of MapEngine?

**Comment by erlandyt** [comment]
Ok, I updated MapEngine and now the command works, However none of the sources other than image work. I tried to use this video https://erland.fi/videos/How%20Auto-Tune%20Works.mp4 with FFmpeg and this https://www.youtube.com/watch?v=_kVZ2iZxBu0 with YouTube.
`/boiler display source 6 ffmpeg true https://erland.fi/videos/How%20Auto-Tune%20Works.mp4`

**Comment by erlandyt** [comment]
The JSON for the frame seems correct (I made this intentionally in another spot).
displays/display_6.json
```json
{
  "id": 6,
  "location": {
    "world": "world",
    "facing": "UP",
    "x1": 591,
    "y1": 115,
    "z1": 971,
    "x2": 597,
    "y2": 115,
    "z2": 964
  },
  "settings": {
    "buffering": true
  },
  "source": {
    "name": "ffmpeg",
    "data": {
      "loop": "true",
      "url": "https://erland.fi/videos/How%20Auto-Tune%20Works.mp4"
    }
  }
}
```
